import { registerEnumType } from "@nestjs/graphql";

export enum Location {
    NPC_BEDROOM = 'NPC_BEDROOM',
    FARMER_HOUSE = 'FARMER_HOUSE',
    TOOL_SHED = 'TOOL_SHED',
    INSIDE_TOOL_SHOP = 'INSIDE_TOOL_SHOP',
    OUTSIDE_TOOL_SHOP = 'OUTSIDE_TOOL_SHOP',
    LIVESTOCK_DEALER_FRONT = 'LIVESTOCK_DEALER_FRONT',
    BEHIND_LIVESTOCK_DEALER = 'BEHIND_LIVESTOCK_DEALER',
    RESTAURANT_FRONT_ROOM = 'RESTAURANT_FRONT_ROOM',
    RESTAURANT_BACK_ROOM = 'RESTAURANT_BACK_ROOM',
    BAR = 'BAR',
    BARN = 'BARN',
    TOWN_SQUARE = 'TOWN_SQUARE',
    MOUNTAIN = 'MOUNTAIN',
    CHURCH = 'CHURCH',
    FLOWER_SHOP = 'FLOWER_SHOP',
}

registerEnumType(Location, {
    name: 'Location',
});
